// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteInfrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoteInfrastructure.Migrations
{
    [DbContext(typeof(NotedbContext))]
    partial class NotedbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Filetag", b =>
                {
                    b.Property<int>("Fileid")
                        .HasColumnType("integer")
                        .HasColumnName("fileid");

                    b.Property<int>("Tagid")
                        .HasColumnType("integer")
                        .HasColumnName("tagid");

                    b.HasKey("Fileid", "Tagid")
                        .HasName("filetags_pkey");

                    b.HasIndex("Tagid");

                    b.ToTable("filetags", (string)null);
                });

            modelBuilder.Entity("NoteDomain.Model.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Folderid")
                        .HasColumnType("integer")
                        .HasColumnName("folderid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("files_pkey");

                    b.HasIndex("Folderid");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("NoteDomain.Model.Fileversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Changelog")
                        .HasColumnType("text")
                        .HasColumnName("changelog");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Fileid")
                        .HasColumnType("integer")
                        .HasColumnName("fileid");

                    b.Property<int>("Versionnumber")
                        .HasColumnType("integer")
                        .HasColumnName("versionnumber");

                    b.HasKey("Id")
                        .HasName("fileversions_pkey");

                    b.HasIndex("Fileid");

                    b.ToTable("fileversions", (string)null);
                });

            modelBuilder.Entity("NoteDomain.Model.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Parentfolderid")
                        .HasColumnType("integer")
                        .HasColumnName("parentfolderid");

                    b.HasKey("Id")
                        .HasName("folders_pkey");

                    b.HasIndex("Parentfolderid");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("NoteDomain.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tags_pkey");

                    b.HasIndex(new[] { "Name" }, "tags_name_key")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Filetag", b =>
                {
                    b.HasOne("NoteDomain.Model.File", null)
                        .WithMany()
                        .HasForeignKey("Fileid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("filetags_fileid_fkey");

                    b.HasOne("NoteDomain.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("Tagid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("filetags_tagid_fkey");
                });

            modelBuilder.Entity("NoteDomain.Model.File", b =>
                {
                    b.HasOne("NoteDomain.Model.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("Folderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("files_folderid_fkey");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("NoteDomain.Model.Fileversion", b =>
                {
                    b.HasOne("NoteDomain.Model.File", "File")
                        .WithMany("Fileversions")
                        .HasForeignKey("Fileid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fileversions_fileid_fkey");

                    b.Navigation("File");
                });

            modelBuilder.Entity("NoteDomain.Model.Folder", b =>
                {
                    b.HasOne("NoteDomain.Model.Folder", "Parentfolder")
                        .WithMany("InverseParentfolder")
                        .HasForeignKey("Parentfolderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("folders_parentfolderid_fkey");

                    b.Navigation("Parentfolder");
                });

            modelBuilder.Entity("NoteDomain.Model.File", b =>
                {
                    b.Navigation("Fileversions");
                });

            modelBuilder.Entity("NoteDomain.Model.Folder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("InverseParentfolder");
                });
#pragma warning restore 612, 618
        }
    }
}
